#!/usr/bin/env bash

GRID_NAME=$1

while true; do
  CONTENTS=$(kontena grid show --token $GRID_NAME)

  if [[ $CONTENTS =~ "error" ]]; then
    echo "Error while getting the token: $CONTENTS, will retry.."
  else
    echo "$CONTENTS"
    break
  fi

  sleep 1
done
