#!/usr/bin/env bash

MASTER_URL=$1

echo "Waiting until master is reachable at $MASTER_URL "
while true; do
  set +e
  STATUS_CODE=$(curl -k --connect-timeout 2 -s -o /dev/null -w "%{http_code}" $MASTER_URL)

  [ "$STATUS_CODE" == 200 ] && break
  set -e

  printf "."
  sleep 1
done

echo "

Endpoint says 200, but it is possible that status code is 200 before actually running. Waiting for it to return some Kontena json.."

while true; do
  set +e
  CONTENTS=$(curl -k --connect-timeout 2 -s $MASTER_URL/v1/ping)
  [[ $CONTENTS =~ "pong" ]] && break
  set -e

  printf "."
  sleep 1
done


echo "

    YEAH! Master is available!

"
