#!/usr/bin/env bash

MASTER_URL=$1

echo "Waiting until master is reachable at $MASTER_URL "
while true; do
  set +e
  STATUS_CODE=$(curl --connect-timeout 2 -s -o /dev/null -w "%{http_code}" $MASTER_URL)

  [ "$STATUS_CODE" == 200 ] && break
  set -e

  printf "."
  sleep 1
done

echo "

ALB says 200, but is probably not ok yet. Waiting for it to return some Kontena json."

while true; do
  set +e
  CONTENTS=$(curl --connect-timeout 2 -s $MASTER_URL)
  [[ $CONTENTS =~ "Kontena Master" ]] && break
  set -e

  printf "."
  sleep 1
done


echo "

    YEAH! Master is available!

"
