#!/usr/bin/env bash

GRID_NAME=$1
TARGET_NODE_COUNT=$2

if [ ! $GRID_NAME ] || [ ! $TARGET_NODE_COUNT ]; then
  echo "params: grid_name target_node_count"
  exit 1
fi

while true; do
  grid_show_output=$(kontena grid show $GRID_NAME)
  echo "$grid_show_output"
  kontena node ls

  if [[ $grid_show_output =~ "nodes: $TARGET_NODE_COUNT of $TARGET_NODE_COUNT" ]]; then
    break
  fi

  sleep 5
done
