#!/usr/bin/env bash
set -e
source recipes/common/params.sh

helpers/apply_stage azure common $RECIPE_NAME

helpers/apply_stage azure virtual_machines/common $RECIPE_NAME
helpers/apply_stage azure virtual_machines/common_masters $RECIPE_NAME

helpers/apply_stage azure virtual_machines/mastermongo $RECIPE_NAME
