#!/usr/bin/env bash
set -e
source recipes/common/params.sh

helpers/apply_stage $PROVIDER_NAME common singlemongo
helpers/apply_stage $PROVIDER_NAME instances/mongosingle singlemongo

MONGO_HOSTNAME=$(bin/output $PROVIDER_NAME singlemongo kontena_mongo_private_dns)
echo "kontena_master_mongodb_host = \"$MONGO_HOSTNAME\"" >> vars/$PROVIDER_NAME-singlemongo.tfvars

helpers/apply_stage $PROVIDER_NAME instances/master singlemongo

MASTER_HOSTNAME=$(bin/output $PROVIDER_NAME singlemongo kontena_instances_master_public_dns)
MASTER_URL="http://$MASTER_HOSTNAME"

source recipes/common/create_grid_and_append_master_uri_and_token.sh

helpers/apply_stage $PROVIDER_NAME instances/node $RECIPE_NAME
helpers/apply_stage $PROVIDER_NAME alb/nodes/http $RECIPE_NAME

NODE_COUNT=$(bin/output $PROVIDER_NAME $RECIPE_NAME kontena_node_count)
helpers/watch_grid_joining $GRID_NAME $NODE_COUNT

helpers/apply_stage $PROVIDER_NAME workarounds/bug_1136 $RECIPE_NAME
