#cloud-config
write_files:
  - path: /etc/systemd/system/docker.service.d/50-kontena.conf
    content: |
      [Service]
      Environment='DOCKER_CGROUPS=--exec-opt native.cgroupdriver=cgroupfs'

  - path: /etc/kontena-mongo.env
    permissions: 0600
    owner: root
    content: |
      KONTENA_MONGO_IMAGE=${kontena_mongo_image}
      KONTENA_MONGO_VERSION=${kontena_mongo_version}
      KONTENA_MONGO_BIND_IP=${kontena_mongo_bind_ip}

  - path: /etc/kontena-log-archiver.env
    permissions: 0600
    owner: root
    content: |
      KONTENA_LOG_ARCHIVER_IMAGE=${kontena_log_archiver_image}
      KONTENA_LOG_ARCHIVER_VERSION=${kontena_log_archiver_version}
      S3_ACCESS_KEY=${kontena_log_archiver_s3_access_key}
      S3_SECRET_KEY=${kontena_log_archiver_s3_secret_key}
      S3_REGION=${kontena_log_archiver_s3_region}
      S3_BUCKET=${kontena_log_archiver_s3_bucket}
      MONGODB_URL=mongodb://mongo/${name}_master

  - path: /etc/kontena-mongo-backup.env
    permissions: 0600
    owner: root
    content: |
      KONTENA_MONGO_BACKUP_IMAGE=${kontena_mongo_backup_image}
      KONTENA_MONGO_BACKUP_VERSION=${kontena_mongo_backup_version}
      MONGODB_HOST=mongo
      INTERVAL=${kontena_mongo_backup_interval}
      S3_ACCESS_KEY_ID=${kontena_mongo_backup_s3_access_key}
      S3_SECRET_ACCESS_KEY=${kontena_mongo_backup_s3_secret_key}
      S3_REGION=${kontena_mongo_backup_s3_region}
      S3_BUCKET=${kontena_mongo_backup_s3_bucket}
      S3_PATH=${kontena_mongo_backup_s3_path}

  - path: /etc/kontena-log-archiver/plugins/bson_monkey.rb
    permissions: 0644
    owner: root
    content: |
      module BSON
        class ObjectId

          def to_msgpack(*a)
            to_s.to_msgpack(*a)
          end

        end
      end

  - path: /etc/kontena-log-archiver/plugins/kontena_formatter.rb
    permissions: 0644
    owner: root
    content: |
      require 'fluent/formatter'

      module Fluent
        module TextFormatter
          class KontenaFormatter < Formatter
            Plugin.register_formatter("kontena_formatter", self)

            include HandleTagAndTimeMixin # If you wish to use tag_key, time_key, etc.
            # config_param :field, :string

            # # This method does further processing. Configuration parameters can be
            # # accessed either via "conf" hash or member variables.
            def configure(conf)
              super
              @field = 'data'
            end

            # This is the method that formats the data output.
            def format(tag, time, record)
              data = record[@field]
              $log.error "#{@field} field key is missing from record." unless data

              "#{Time.at(time).iso8601} #{tag} #{data}\n"
            end
          end
        end
      end

  - path: /etc/kontena-log-archiver/etc/fluent.conf
    permissions: 0644
    owner: root
    content: |
      <source>
        type mongo_tail
        url "#{ENV['MONGODB_URL']}"
        collection container_logs
        tag_key name
        time_key created_at
        id_store_collection container_logs_tail
      </source>

      <match **>
        @type copy
        <store>
          @type s3

          aws_key_id "#{ENV['S3_ACCESS_KEY']}"
          aws_sec_key "#{ENV['S3_SECRET_KEY']}"
          s3_bucket "#{ENV['S3_BUCKET']}"
          s3_region "#{ENV['S3_REGION']}"
          path master_logs_minutely

          buffer_type memory
          buffer_chunk_limit 256m
          buffer_queue_limit 128

          store_as gzip
          format kontena_formatter
          include_time_key true
          include_tag_key true

          s3_object_key_format %{path}/%{time_slice}_%{index}.log.%{file_extension}
          time_slice_format %Y%m%d-%H
          time_slice_wait 10m

          flush_interval 60s

          utc
        </store>
      </match>

coreos:
  locksmith:
    window-start: ${coreos_locksmith_window_start}
    window-length: ${coreos_locksmith_window_length}
  update:
    reboot-strategy: ${coreos_update_reboot_strategy}

  units:
    - name: kontena-server-mongo.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=kontena-server-mongo
        After=network-online.target
        After=docker.service
        Description=Kontena Server MongoDB
        Documentation=http://www.mongodb.org/
        Requires=network-online.target
        Requires=docker.service

        [Service]
        Restart=always
        RestartSec=5
        EnvironmentFile=/etc/kontena-mongo.env
        EnvironmentFile=-/etc/kontena-mongo.custom.env
        ExecStartPre=/usr/bin/docker pull $${KONTENA_MONGO_IMAGE}:$${KONTENA_MONGO_VERSION}
        ExecStartPre=-/usr/bin/docker create --name=kontena-server-mongo-data $${KONTENA_MONGO_IMAGE}:$${KONTENA_MONGO_VERSION}
        ExecStartPre=-/usr/bin/docker stop kontena-server-mongo
        ExecStartPre=-/usr/bin/docker rm kontena-server-mongo
        ExecStart=/usr/bin/docker run --name=kontena-server-mongo \
          --volumes-from=kontena-server-mongo-data \
          --publish "27017:27017" \
          $${KONTENA_MONGO_IMAGE}:$${KONTENA_MONGO_VERSION} mongod --smallfiles --bind_ip "$${KONTENA_MONGO_BIND_IP}"
        ExecStop=/usr/bin/docker stop kontena-server-mongo

    - name: kontena-log-archiver.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=kontena-log-archiver
        After=kontena-server-mongo.service
        Description=Kontena Log Archiver
        Documentation=https://github.com/kontena/kontena-log-archiver
        Requires=kontena-server-mongo.service

        [Service]
        Restart=always
        RestartSec=5
        EnvironmentFile=/etc/kontena-log-archiver.env
        EnvironmentFile=-/etc/kontena-log-archiver.custom.env
        ExecStartPre=/usr/bin/docker pull $${KONTENA_LOG_ARCHIVER_IMAGE}:$${KONTENA_LOG_ARCHIVER_VERSION}
        ExecStartPre=-/usr/bin/docker stop kontena-log-archiver
        ExecStartPre=-/usr/bin/docker rm kontena-log-archiver
        ExecStartPre=-/usr/bin/docker exec -it kontena-server-mongo mongo --eval 'db.createCollection("container_logs_tail", {capped: true, size: 5242880})' localhost/${name}_master
        ExecStart=/usr/bin/docker run --name=kontena-log-archiver \
          -e S3_ACCESS_KEY=$${S3_ACCESS_KEY} \
          -e S3_SECRET_KEY=$${S3_SECRET_KEY} \
          -e S3_REGION=$${S3_REGION} \
          -e S3_BUCKET=$${S3_BUCKET} \
          -e MONGODB_URL=$${MONGODB_URL} \
          --link kontena-server-mongo:mongo \
          -v /etc/kontena-log-archiver/etc:/fluentd/etc \
          -v /etc/kontena-log-archiver/plugins:/fluentd/plugins \
          $${KONTENA_LOG_ARCHIVER_IMAGE}:$${KONTENA_LOG_ARCHIVER_VERSION}
        ExecStop=/usr/bin/docker stop kontena-log-archiver

    - name: kontena-mongo-backup.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=kontena-mongo-backup
        After=kontena-server-mongo.service
        Description=Kontena Server MongoDB
        Documentation=http://www.mongodb.org/
        Requires=kontena-server-mongo.service

        [Service]
        Restart=always
        RestartSec=5
        EnvironmentFile=/etc/kontena-mongo-backup.env
        EnvironmentFile=-/etc/kontena-mongo-backup.custom.env
        ExecStartPre=/usr/bin/docker pull $${KONTENA_MONGO_BACKUP_IMAGE}:$${KONTENA_MONGO_BACKUP_VERSION}
        ExecStartPre=-/usr/bin/docker stop kontena-mongo-backup
        ExecStartPre=-/usr/bin/docker rm kontena-mongo-backup
        ExecStart=/usr/bin/docker run --name=kontena-mongo-backup \
          -e MONGODB_HOST=$${MONGODB_HOST} \
          -e INTERVAL=$${INTERVAL} \
          -e S3_ACCESS_KEY_ID=$${S3_ACCESS_KEY_ID} \
          -e S3_SECRET_ACCESS_KEY=$${S3_SECRET_ACCESS_KEY} \
          -e S3_REGION=$${S3_REGION} \
          -e S3_BUCKET=$${S3_BUCKET} \
          -e S3_PATH=$${S3_PATH} \
          --link kontena-server-mongo:$${MONGODB_HOST} \
          $${KONTENA_MONGO_BACKUP_IMAGE}:$${KONTENA_MONGO_BACKUP_VERSION}
