#!/usr/bin/env bash
set -e
GRID_NAME=$1
RECIPE_NAME=nodegrid

[ ! "$GRID_NAME" ] && echo "params: GRID_NAME" && exit 1

nodes=$(kontena node ls | tail -n +2 | cut -f 1 -d " ")
for node in $nodes; do
  kontena node rm --force $node
  echo "removed node $node"
done

kontena grid rm --force $GRID_NAME

bin/destroy aws $RECIPE_NAME
