#!/usr/bin/env bash
set -e
GRID_NAME=$1

source recipes/common/recipe_name.sh

[ ! "$GRID_NAME" ] && echo "params: GRID_NAME" && exit 1

source recipes/common/kontena/service_rm_all.sh
source recipes/common/kontena/node_rm_all.sh
source recipes/common/kontena/grid_rm.sh

bin/destroy aws $RECIPE_NAME
