#cloud-config
write_files:
  - path: /etc/systemd/system/docker.service.d/50-kontena.conf
    content: |
        [Service]
        Environment='DOCKER_CGROUPS=--exec-opt native.cgroupdriver=cgroupfs'

  - path: /etc/kontena-mongo.env
    permissions: 0600
    owner: root
    content: |
      KONTENA_MONGO_IMAGE=${kontena_mongo_image}
      KONTENA_MONGO_VERSION=${kontena_mongo_version}
      KONTENA_MONGO_BIND_IP=${kontena_mongo_bind_ip}

coreos:
  locksmith:
    window-start: ${coreos_locksmith_window_start}
    window-length: ${coreos_locksmith_window_length}
  update:
    reboot-strategy: ${coreos_update_reboot_strategy}

  units:
    - name: kontena-server-mongo.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=kontena-server-mongo
        After=network-online.target
        After=docker.service
        Description=Kontena Server MongoDB
        Documentation=http://www.mongodb.org/
        Requires=network-online.target
        Requires=docker.service

        [Service]
        Restart=always
        RestartSec=5
        EnvironmentFile=/etc/kontena-mongo.env
        EnvironmentFile=-/etc/kontena-mongo.custom.env
        ExecStartPre=/usr/bin/docker pull $${KONTENA_MONGO_IMAGE}:$${KONTENA_MONGO_VERSION}
        ExecStartPre=-/usr/bin/docker create --name=kontena-server-mongo-data $${KONTENA_MONGO_IMAGE}:$${KONTENA_MONGO_VERSION}
        ExecStartPre=-/usr/bin/docker stop kontena-server-mongo
        ExecStartPre=-/usr/bin/docker rm kontena-server-mongo
        ExecStart=/usr/bin/docker run --name=kontena-server-mongo \
          --volumes-from=kontena-server-mongo-data \
          --publish "27017:27017" \
          $${KONTENA_MONGO_IMAGE}:$${KONTENA_MONGO_VERSION} mongod --smallfiles --bind_ip "$${KONTENA_MONGO_BIND_IP}"
        ExecStop=/usr/bin/docker stop kontena-server-mongo
