#cloud-config
write_files:
  - path: /etc/systemd/system/docker.service.d/50-kontena.conf
    content: |
      [Service]
      Environment='DOCKER_CGROUPS=--exec-opt native.cgroupdriver=cgroupfs'

  - path: /etc/kontena-server.env
    permissions: 0600
    owner: root
    content: |
      KONTENA_MASTER_IMAGE=${kontena_master_image}
      KONTENA_MASTER_VERSION=${kontena_master_version}
      VAULT_IV=${kontena_master_vault_iv}
      VAULT_KEY=${kontena_master_vault_key}
      INITIAL_ADMIN_CODE=${kontena_master_initial_admin_code}
      WEB_CONCURRENCY=${kontena_master_web_concurrency}
      MAX_THREADS=${kontena_master_max_threads}
      MONGODB_URI=${kontena_master_mongodb_uri}

  - path: /etc/kontena-haproxy.env
    permissions: 0600
    owner: root
    content: |
      KONTENA_HAPROXY_IMAGE=${kontena_haproxy_image}
      KONTENA_HAPROXY_VERSION=${kontena_haproxy_version}
      SSL_CERT="/etc/kontena-server.pem"

  - path: /opt/bin/kontena-haproxy.sh
    permissions: 0755
    owner: root
    content: |
      #!/bin/sh
      if [ -n "$SSL_CERT" ]; then
        SSL_CERT=$(awk 1 ORS='\\n' $SSL_CERT)
      else
        SSL_CERT="**None**"
      fi
      /usr/bin/docker run --name=kontena-server-haproxy \
        --link kontena-server-api:kontena-server-api \
        -e SSL_CERT="$SSL_CERT" -e BACKEND_PORT=9292 \
        -p 80:80 -p 443:443 $KONTENA_HAPROXY_IMAGE:$KONTENA_HAPROXY_VERSION

coreos:
  locksmith:
    window-start: ${coreos_locksmith_window_start}
    window-length: ${coreos_locksmith_window_length}
  update:
    reboot-strategy: ${coreos_update_reboot_strategy}

  units:
    - name: kontena-server-api.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=kontena-server-api
        Before=kontena-server-haproxy.service
        Wants=kontena-server-haproxy.service
        After=network-online.target
        After=docker.service
        Description=Kontena Server
        Documentation=http://www.kontena.io/
        Requires=network-online.target
        Requires=docker.service

        [Service]
        Restart=always
        RestartSec=5
        EnvironmentFile=/etc/kontena-server.env
        EnvironmentFile=-/etc/kontena-server.custom.env
        ExecStartPre=-/usr/bin/docker stop kontena-server-api
        ExecStartPre=-/usr/bin/docker rm kontena-server-api
        ExecStartPre=/usr/bin/docker pull $${KONTENA_MASTER_IMAGE}:$${KONTENA_MASTER_VERSION}
        ExecStart=/usr/bin/docker run --name kontena-server-api \
          -e MONGODB_URI=$${MONGODB_URI} \
          -e WEB_CONCURRENCY=$${WEB_CONCURRENCY} \
          -e MAX_THREADS=$${MAX_THREADS} \
          -e VAULT_KEY=$${VAULT_KEY} -e VAULT_IV=$${VAULT_IV} \
          -e INITIAL_ADMIN_CODE=$${INITIAL_ADMIN_CODE} \
          $${KONTENA_MASTER_IMAGE}:$${KONTENA_MASTER_VERSION}
        ExecStop=/usr/bin/docker stop kontena-server-api

    - name: kontena-server-haproxy.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=kontena-server-haproxy
        After=network-online.target
        After=docker.service
        Description=Kontena Server HAProxy
        Documentation=http://www.kontena.io/
        Requires=network-online.target
        Requires=docker.service
        Requires=kontena-server-api.service

        [Service]
        Restart=always
        RestartSec=5
        EnvironmentFile=/etc/kontena-haproxy.env
        EnvironmentFile=-/etc/kontena-haproxy.custom.env
        ExecStartPre=-/usr/bin/docker stop kontena-server-haproxy
        ExecStartPre=-/usr/bin/docker rm kontena-server-haproxy
        ExecStartPre=/usr/bin/docker pull $${KONTENA_HAPROXY_IMAGE}:$${KONTENA_HAPROXY_VERSION}
        ExecStart=/opt/bin/kontena-haproxy.sh
        ExecStop=/usr/bin/docker stop kontena-server-haproxy
